model:
    # ===== Encoder =====
    encoder:
        match_scalar:
            ball_position:
                input_dim: 3
                output_dim: 32
            ball_direction:
                input_dim: 3
                output_dim: 32
            ball_rotation:
                input_dim: 3
                output_dim: 32
            ball_owned_team:
                input_dim: 3
                output_dim: 32
            ball_owned_player:
                input_dim: 12
                output_dim: 32
            active_player:
                input_dim: 11
                output_dim: 32
            designated_player:
                input_dim: 11
                output_dim: 32
            active_player_sticky_actions:
                input_dim: 10
                output_dim: 64
            score:
                input_dim: 22
                output_dim: 64
            steps_left:
                input_dim: 30
                output_dim: 128
            game_mode:
                input_dim: 7
                output_dim: 128
        player:
            encoder_type: 'transformer'  # ['transformer', 'spatial']
            transformer:
                player_num: 22
                player_attr_dim:
                    team: 2
                    index: 11
                    position: 2
                    direction: 2
                    tired_factor: 1
                    yellow_card: 2
                    active: 2
                    role: 10
                input_dim: 1
                head_dim: 64
                hidden_dim: 128
                output_dim: 1
                head_num: 2
                mlp_num: 2
                layer_num: 3
                dropout_ratio: 1
            spatial:
                resblock_num: 4
                fc_dim: 256
                project_dim: 32
                down_channels: [64, 128]
                activation: 'relu'
                norm_type: 'BN'
                player_attr_dim:
                    team: 2
                    index: 11
                    position: 2
                    direction: 2
                    tired_factor: 1
                    yellow_card: 2
                    active: 2
                    role: 10
    # ===== Policy =====
    policy:
        res_block:
            hidden_dim: 1024
            block_num: 3
        dqn:
            dueling: True
            a_layer_num:  2
            v_layer_num:  2
        action_dim: 19
