common:
    name: SumoDqnDistConfig
    time_wrapper_type: cuda
    save_path: '.'
    load_path: ''
replay_buffer:
    meta_maxlen: 10000
    max_reuse: 8
    min_sample_ratio: 1
    unroll_len: 1
    enable_track_used_data: True
learner:
    learner_type: 'atari_a2c'
    import_names: ['app_zoo.atari.worker.atari_ac_learner']
    use_cuda: True
    use_distributed: False
    max_iterations: 10000000
    unroll_len: 1
    learning_rate: 0.004
    weight_decay: 0.0001
    data:
        batch_size: 64
        chunk_size: 16
        num_workers: 0
    a2c:
        gamma: 0.9
        gae_lambda: 0.95
        value_weight: 0.5
        entropy_weight: 0.001
    hook:
        save_ckpt_after_iter:
            name: save_ckpt_after_iter
            type: save_ckpt
            priority: 40
            position: after_iter
            ext_args:
                freq: 500
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 10
    communication:
        type: 'flask_fs'
        upstream_ip: '127.0.0.1'
        upstream_port: 13297
        learner_ip: 127.0.0.1
        learner_port: 13295
        heartbeats_freq: 50
        send_agent_freq: 10
        send_train_info_freq: 10
        path_traj: '.'
        path_agent: '.'
        restore: False
model:
    embedding_dim: 128
env:
    env_num: 2
    env_id: 'PongNoFrameskip-v4'
    frame_stack: 4
    is_train: True
actor:
    actor_type: 'atari_ac'
    import_names: ['app_zoo.atari.worker.atari_actor_controller']
    use_cuda: False
    print_freq: 100
    communication:
        type: flask_fs  # ['single_machine', 'flask_fs']
        path_agent: '.'
        path_traj: '.'
        heartbeats_freq: 30
        upstream_ip: '127.0.0.1'
        upstream_port: 13296
league:
    league_type: 'static'
    import_names: ['nervex.league.static_league_manager']
    use_pretrain_init_historical: False
    player_category: ['main']
    task:
        data_push_length: 64
        episode_num: 4
        use_eps: False
        adder_kwargs:
            use_gae: True
            gamma: 0.9  # a2c.gamma
            gae_lambda: 0.95  # a2c.gae_lambda
    communication:
        type: 'flask_fs'
        file_system_type: 'normal'  # ['normal', 'ceph']
        path_agent: '.'
        path_traj: '.'
system:
    manager_ip: '127.0.0.1'
    manager_port: 13296
    coordinator_ip: '127.0.0.1'
    coordinator_port: 13297
    resume_dir: '.'
    manager_resume_path:
    coordinator_resume_path:
    coordinator_check_dead_learner_freq: 300
    league_manager_ip: '127.0.0.1'
    league_manager_port: 13298
    actor_num: 2
