common:
    name: PendulumDdpgDistConfig
    time_wrapper_type: cuda
    save_path: '.'
    load_path: ''
replay_buffer:
    meta_maxlen: 10000
    max_reuse: 8
    min_sample_ratio: 1
    unroll_len: 1
    enable_track_used_data: True
learner:
    learner_type: 'pendulum_ddpg'
    import_names: ['app_zoo.classic_control.pendulum.worker.learner.pendulum_ddpg_learner']
    use_cuda: True
    use_distributed: True
    max_iterations: 10000000
    unroll_len: 1
    learning_rate: 0.001
    weight_decay: 0.0001
    reward_weights:
        'queue_len': 1.0
    data:
        batch_size: 64
        chunk_size: 16
        num_workers: 4
    ddpg:
        discount_factor: 0.95
        is_double: True
        dueling: True
        actor_update_freq: 1
    hook:
        save_ckpt_after_iter:
            name: save_ckpt_after_iter
            type: save_ckpt
            priority: 40
            position: after_iter
            ext_args:
                freq: 500
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 1
    communication:
        type: 'flask_fs'
        upstream_ip: '10.5.36.31'
        upstream_port: 13297
        learner_ip: 'auto'
        learner_port: 13295
        heartbeats_freq: 50
        send_agent_freq: 10
        send_train_info_freq: 10
        path_traj: '.'
        path_agent: '.'
        restore: False
model:
    placeholder: 'placeholder'
actor:
    actor_type: 'pendulum'
    import_names: ['app_zoo.classic_control.pendulum.worker.actor.pendulum_actor_controller']
    use_cuda: True
    print_freq: 100
    communication:
        type: flask_fs # ['single_machine', 'flask_fs']
        path_agent: '.'
        path_traj: '.'
        heartbeats_freq: 30
        upstream_ip: '10.5.36.31'
        upstream_port: 13296
league:
    league_type: 'solo'
    import_names: ['nervex.league.solo_league_manager']
    use_pretrain_init_historical: False
    player_category: ['main']
    active_players:
        solo_active_player: 1
    solo_active_player:
        one_phase_step: 1e9
        forward_kwargs:
            exploration:
                exploration_type: ['eps', 'gauss_noise'] # ['eps', 'gauss_noise', 'ou_noise']
                eps_kwargs:
                    start: 0.95
                    end: 0.05
                    decay_len: 10000
                noise_kwargs:
                    mu: 0.0
                    sigma: 0.1
                    range: 0.5
        env_kwargs:
            env_num: 2
            episode_num: 2
            env_cfg:
                env_type: 'fake' # ['normal', 'fake']
        adder_kwargs:
            use_gae: False
            data_push_length: 64
        job:
            agent_update_freq: 30 # second
            compressor: 'none'
    communication:
        type: 'flask_fs'
        file_system_type: 'normal' # ['normal', 'ceph']
        path_agent: '.'
        path_traj: '.'
system:
    manager_ip: '10.5.36.31'
    manager_port: 13296
    coordinator_ip: '10.5.36.31'
    coordinator_port: 13297
    resume_dir: '.'
    manager_resume_path:
    coordinator_resume_path:
    coordinator_check_dead_learner_freq: 300
    league_manager_ip: 'auto'
    league_manager_port: 13298
    actor_num: 2
