model:
    use_value_network: True
    use_battle_reward: False
train:
    trajectory_len: 4
    batch_size: 3
    use_cuda: False
    action_output_types:
        action_type: logit
        delay: value
        queued: logit
        selected_units: logit
        target_units: logit
        target_location: logit
    kl:
        action_type_kl_seconds: 240
    vtrace:
        min_clip: 1.0
    upgo:
        min_clip: 1.0
    use_target_state: True
    temperature: 0.8
    loss_weights:
        baseline:
            winloss: 10.0
            build_order: 1.0
            built_unit: 1.0
            effect: 1.0
            upgrade: 1.0
            battle: 0.5
        pg:
            winloss: 1.0
            build_order: 4.0
            built_unit: 6.0
            effect: 6.0
            upgrade: 6.0
            battle: 1.0
        upgo:
            winloss: 1.0
        kl: 0.002
        action_type_kl: 0.1
        entropy: 0.0001
    learning_rate: 0.001
    weight_decay: 0.0001
