model:
    use_value_network: False
    policy:
        head:
            location_head:
                output_type: 'cls'
train:
    batch_size: 2
    trajectory_len: 3
    use_cuda: False
    criterion:
        type: 'soft_focal_loss'  # ['cross_entropy', 'label_smooth', 'soft_focal_loss']
        action_type: 'normal'
    temperature: 1.0
    learning_rate: 0.001
    weight_decay: 0.0001
    parallel: True
