@startuml serial_learner
header Serial Pipeline
title Serial Learner

|#green|serial_controller|
|#orange|policy|
|learner|

|#green|serial_controller|
start
:init learner, \nset its learn_mode policy;
repeat
  |learner|
  :learner call before_iter hook;
  |#orange|policy|
  :policy reset;
  :policy data_preprocess;
  :policy forward (including \nbackward and grad update);
  |learner|
  :learner update log_buffer_info and priority_info;
  :learner update learn_info;
repeat while (train iteration is not enough?)
stop
@enduml
