@startuml serial_collector
header Serial Pipeline
title Serial Collector

|#green|serial_controller|
|#pink|env_manager|
|#orange|policy|
|collector|

|#green|serial_controller|
start
:init collector, set its \nenv_manager and \ncollect_mode policy;
|#pink|env_manager|
:env reset;
repeat
  |#orange|policy|
  :policy data_preprocess;
  :policy forward with obs;
  :policy data_postprocess;
  |#pink|env_manager|
  :env step with action;
  |#orange|policy|
  :policy process_transition;
  |collector|
  :collector save transition in cache;
  if (for every env: \n - env i is done?) then (yes)
    |#orange|policy|
    :policy get_train_sample from cache;
    |collector|
    :collector save train_sample for return;
    if (env i is done?) then (yes)
      |#pink|env_manager|
      :env i reset;
      |#orange|policy|
      :policy collect_mode reset;
      |collector|
      :collector log episode_collect_info;
    endif
  endif
repeat while (generated traj data is not enough?)
|collector|
:collector log statistics;
:collector return collect_data;
stop

@enduml
