@startuml serial_evaluator
header Serial Pipeline
title Serial Evaluator

|#green|serial_controller|
|#pink|env_manager|
|#orange|policy|
|evaluator|

|#green|serial_controller|
start
:init evaluator, set its \nenv_manager and \neval_mode policy;
|#pink|env_manager|
:env reset;
repeat
  |#orange|policy|
  :policy data_preprocess;
  :policy forward with obs;
  :policy data_postprocess;
  |#pink|env_manager|
  :env step with action;
  |evaluator|
  if (for every env: env i is done?) then (yes)
    |#pink|env_manager|
    :env i reset;
    |#orange|policy|
    :policy eval_mode reset;
    |evaluator|
    :evaluator log episode_eval_info;
  endif
  :evaluator log statistics;
repeat while (eval episodes are not enough?)
|evaluator|
:evaluator return eval_reward\n(episode-averaged);
stop
@enduml
