common:
    name: SumoDqnConfig
    time_wrapper_type: cuda
    save_path: '.'
    load_path: ''
learner:
    use_cuda: False
    use_distributed: False
    max_iterations: 1000000
    batch_size: 64
    learning_rate: 0.001
    weight_decay: 0.0001
    reward_weights:
        'queue_len': 1.0
    dqn:
        total_frame_num: 1000000
        max_epoch_frame: 2000
        buffer_length: 10000
        update_target_freq: 100
        discount_factor: 0.95
        is_double: True
    hook:
        save_ckpt_after_iter:
            name: save_ckpt_after_iter
            type: save_ckpt
            priority: 40
            position: after_iter
            ext_args:
                freq: 500
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 50
env:
    env_num: 4
    env_type: 'normal'
