# flake8: noqa
"""
Generated by map_size_gen.py, containing information for each map in MAPS dict
key: map_name (formatted, without spaces and LE)
value: (battle_net, map_path, map_size (cropped to game boundary)(x,y),uncropped_map_size, localized_names, localized_names_without_spaces)
"""

MAPS = {
    'BelShirVestige': (
        "Bel'Shir Vestige LE", 'Ladder2017Season1\\BelShirVestigeLE.SC2Map', [128, 144], [144, 160], '拜舍尔遗迹 - 天梯版（虚空）',
        '拜舍尔遗迹-天梯版（虚空）', 'BelShirVestigeLE'
    ),
    'CactusValley': (
        'Cactus Valley LE', 'Ladder2017Season1\\CactusValleyLE.SC2Map', [156, 156], [192, 192], 'Cactus Valley L E ',
        'CactusValleyLE', 'CactusValleyLE'
    ),
    'Honorgrounds': (
        'Honorgrounds LE', 'Ladder2017Season1\\HonorgroundsLE.SC2Map', [156, 156], [176, 176], '荣耀战场 - 天梯版', '荣耀战场-天梯版',
        'HonorgroundsLE'
    ),
    'NewkirkPrecinct': (
        'Newkirk Precinct TE', 'Ladder2017Season1\\NewkirkPrecinctTE.SC2Map', [172, 124], [224, 168],
        '新柯尔克辖区 - 锦标赛版 (虚空)', '新柯尔克辖区-锦标赛版(虚空)', 'NewkirkPrecinctTE'
    ),
    'PaladinoTerminal': (
        'Paladino Terminal LE', 'Ladder2017Season1\\PaladinoTerminalLE.SC2Map', [144, 112], [160, 184], '帕拉蒂诺中转站 - 天梯版',
        '帕拉蒂诺中转站-天梯版', 'PaladinoTerminalLE'
    ),
    'BloodBoil': (
        'Blood Boil LE', 'Ladder2017Season2\\BloodBoilLE.SC2Map', [132, 180], [152,
                                                                               208], '血沸 - 天梯版', '血沸-天梯版', 'BloodBoilLE'
    ),
    'DefendersLanding': (
        "Defender's Landing LE", 'Ladder2017Season2\\DefendersLandingLE.SC2Map', [148, 128], [168, 152], '保卫者登陆场 - 天梯版',
        '保卫者登陆场-天梯版', 'DefendersLandingLE'
    ),
    'ProximaStation': (
        'Proxima Station LE', 'Ladder2017Season2\\ProximaStationLE.SC2Map', [172, 152], [200, 200], '普罗西玛空间站 - 天梯版',
        '普罗西玛空间站-天梯版', 'ProximaStationLE'
    ),
    'Sequencer': (
        'Sequencer LE', 'Ladder2017Season2\\SequencerLE.SC2Map', [132,
                                                                  164], [184,
                                                                         208], '十六宫格 - 天梯版', '十六宫格-天梯版', 'SequencerLE'
    ),
    'Acolyte': (
        'Acolyte LE', 'Ladder2017Season3\\AcolyteLE.SC2Map', [136, 168], [168, 200], '紫晶卫 - 天梯版', '紫晶卫-天梯版', 'AcolyteLE'
    ),
    'Frost': (
        'Frost LE', 'Ladder2017Season3\\FrostLE.SC2Map', [156, 160], [184, 184], '寒霜 - 天梯版（虚空）', '寒霜-天梯版（虚空）', 'FrostLE'
    ),
    'Interloper': (
        'Interloper LE', 'Ladder2017Season3\\InterloperLE.SC2Map', [132,
                                                                    140], [152,
                                                                           176], '闯星 - 天梯版', '闯星-天梯版', 'InterloperLE'
    ),
    'MechDepot': (
        'Mech Depot LE', 'Ladder2017Season3\\MechDepotLE.SC2Map', [152, 152], [184, 176], '机甲维护站 - 天梯版', '机甲维护站-天梯版',
        'MechDepotLE'
    ),
    'AbyssalReef': (
        'Abyssal Reef LE', 'Ladder2017Season4\\AbyssalReefLE.SC2Map', [152, 136], [200, 176], '深海暗礁 - 天梯版', '深海暗礁-天梯版',
        'AbyssalReefLE'
    ),
    'AscensiontoAiur': (
        'Ascension to Aiur LE', 'Ladder2017Season4\\AscensiontoAiurLE.SC2Map', [160, 132], [176, 152], '飞升艾尔 - 天梯版',
        '飞升艾尔-天梯版', 'AscensiontoAiurLE'
    ),
    'BattleontheBoardwalk': (
        'Battle on the Boardwalk LE', 'Ladder2017Season4\\BattleontheBoardwalkLE.SC2Map', [160, 108], [192, 128],
        'Battle on the Boardwalk LE', 'BattleontheBoardwalkLE', 'BattleontheBoardwalkLE'
    ),
    'Odyssey': (
        'Odyssey LE', 'Ladder2017Season4\\OdysseyLE.SC2Map', [152, 156], [168, 184], '奥德赛 - 天梯版', '奥德赛-天梯版', 'OdysseyLE'
    ),
    'Abiogenesis': (
        'Abiogenesis LE', 'Ladder2018Season1\\AbiogenesisLE.SC2Map', [124, 140], [168, 192], 'Abiogenesis LE',
        'AbiogenesisLE', 'AbiogenesisLE'
    ),
    'Backwater': (
        'Backwater LE', 'Ladder2018Season1\\BackwaterLE.SC2Map', [146,
                                                                  136], [168,
                                                                         160], '死水之地 - 天梯版', '死水之地-天梯版', 'BackwaterLE'
    ),
    'Eastwatch': (
        'Eastwatch LE', 'Ladder2018Season1\\EastwatchLE.SC2Map', [148, 152], [176, 176], 'Eastwatch LE', 'EastwatchLE',
        'EastwatchLE'
    ),
    'NeonVioletSquare': (
        'Neon Violet Square LE', 'Ladder2018Season1\\NeonVioletSquareLE.SC2Map', [148, 148], [200, 192],
        'Neon Violet Square LE', 'NeonVioletSquareLE', 'NeonVioletSquareLE'
    ),
    '16Bit': (
        '16-Bit LE', 'Ladder2018Season2\\16-BitLE.SC2Map', [140, 156], [160, 184], '16位-天梯版', '16位-天梯版', '16-BitLE'
    ),
    'Catalyst': (
        'Catalyst LE', 'Ladder2018Season2\\CatalystLE.SC2Map', [136, 144], [184,
                                                                            184], '汇龙岛 - 天梯版', '汇龙岛-天梯版', 'CatalystLE'
    ),
    'DarknessSanctuary': (
        'Darkness Sanctuary LE', 'Ladder2018Season2\\DarknessSanctuaryLE.SC2Map', [164, 164], [176, 176], '黑暗避难所-天梯版',
        '黑暗避难所-天梯版', 'DarknessSanctuaryLE'
    ),
    'Redshift': (
        'Redshift LE', 'Ladder2018Season2\\RedshiftLE.SC2Map', [124, 152], [152, 184], '红移-天梯版', '红移-天梯版', 'RedshiftLE'
    ),
    'AcidPlant': (
        'Acid Plant LE', 'Ladder2018Season3\\AcidPlantLE.SC2Map', [148,
                                                                   136], [168,
                                                                          184], '强酸工厂 - 天梯版', '强酸工厂-天梯版', 'AcidPlantLE'
    ),
    'Dreamcatcher': (
        'Dreamcatcher LE', 'Ladder2018Season3\\DreamcatcherLE.SC2Map', [136, 136], [168, 176], '逐梦之地-天梯版', '逐梦之地-天梯版',
        'DreamcatcherLE'
    ),
    'Fracture': (
        'Fracture LE', 'Ladder2018Season3\\FractureLE.SC2Map', [144, 124], [224,
                                                                            184], '冰棱裂境-天梯版', '冰棱裂境-天梯版', 'FractureLE'
    ),
    'LostandFound': (
        'Lost and Found LE', 'Ladder2018Season3\\LostandFoundLE.SC2Map', [144, 128], [168, 168], '失而复得-天梯版', '失而复得-天梯版',
        'LostandFoundLE'
    ),
    'Blueshift': (
        'Blueshift LE', 'Ladder2018Season4\\BlueshiftLE.SC2Map', [136, 136], [176,
                                                                              184], '蓝移-天梯版', '蓝移-天梯版', 'BlueshiftLE'
    ),
    'CeruleanFall': (
        'Cerulean Fall LE', 'Ladder2018Season4\\CeruleanFallLE.SC2Map', [148, 136], [168, 160], '缀蓝秋原-天梯版', '缀蓝秋原-天梯版',
        'CeruleanFallLE'
    ),
    'ParaSite': (
        'Para Site LE', 'Ladder2018Season4\\ParaSiteLE.SC2Map', [140, 152], [176,
                                                                             184], '地龙岛-天梯版', '地龙岛-天梯版', 'ParaSiteLE'
    ),
    'Stasis': (
        'Stasis LE', 'Ladder2018Season4\\StasisLE.SC2Map', [152, 128], [168, 144], '静滞区 - 天梯版', '静滞区-天梯版', 'StasisLE'
    ),
    'Automaton': (
        'Automaton LE', 'Ladder2019Season1\\AutomatonLE.SC2Map', [148,
                                                                  148], [184,
                                                                         192], '机械城 - 天梯版', '机械城-天梯版', 'AutomatonLE'
    ),
    'PortAleksander': (
        'Port Aleksander LE', 'Ladder2019Season1\\PortAleksanderLE.SC2Map', [156, 140], [176, 160], '亚历山大港 - 天梯版',
        '亚历山大港-天梯版', 'PortAleksanderLE'
    ),
    'YearZero': (
        'Year Zero LE', 'Ladder2019Season1\\YearZeroLE.SC2Map', [166, 128], [216,
                                                                             192], '零纪元-天梯版', '零纪元-天梯版', 'YearZeroLE'
    ),
    'CyberForest': (
        'Cyber Forest LE', 'Ladder2019Season2\\CyberForestLE.SC2Map', [128, 148], [168, 184], '赛博森林-天梯版', '赛博森林-天梯版',
        'CyberForestLE'
    ),
    'KairosJunction': (
        'Kairos Junction LE', 'Ladder2019Season2\\KairosJunctionLE.SC2Map', [120, 140], [152, 168], '凯罗斯中转站-天梯版',
        '凯罗斯中转站-天梯版', 'KairosJunctionLE'
    ),
    'KingsCove': (
        "King's Cove LE", 'Ladder2019Season2\\KingsCoveLE.SC2Map', [152,
                                                                    148], [176,
                                                                           176], '国王藏宝地-天梯版', '国王藏宝地-天梯版', 'KingsCoveLE'
    ),
    'NewRepugnancy': (
        'New Repugnancy LE', 'Ladder2019Season2\\NewRepugnancyLE.SC2Map', [152, 120], [184, 144], '宿怨战场-天梯版',
        '宿怨战场-天梯版', 'NewRepugnancyLE'
    ),
    'TurboCruise84': (
        "Turbo Cruise '84 LE", 'Ladder2019Season2\\TurboCruise84LE.SC2Map', [140, 116], [192, 176], '涡轮巡飞城-天梯版',
        '涡轮巡飞城-天梯版', 'TurboCruise84LE'
    ),
    'Acropolis': (
        'Acropolis LE', 'Ladder2019Season3\\AcropolisLE.SC2Map', [140,
                                                                  136], [176,
                                                                         184], '滨海卫城 - 天梯版', '滨海卫城-天梯版', 'AcropolisLE'
    ),
    'DiscoBloodbath': (
        'Disco Bloodbath LE', 'Ladder2019Season3\\DiscoBloodbathLE.SC2Map', [148, 132], [200, 184], '浴血迪斯科 - 天梯版',
        '浴血迪斯科-天梯版', 'DiscoBloodbathLE'
    ),
    'Ephemeron': (
        'Ephemeron LE', 'Ladder2019Season3\\EphemeronLE.SC2Map', [132,
                                                                  148], [160,
                                                                         168], '伊菲莫隆 - 天梯版', '伊菲莫隆-天梯版', 'EphemeronLE'
    ),
    'Thunderbird': (
        'Thunderbird LE', 'Ladder2019Season3\\ThunderbirdLE.SC2Map', [140,
                                                                      140], [192,
                                                                             168], '雷鸟 - 天梯版', '雷鸟-天梯版', 'ThunderbirdLE'
    ),
    'Triton': (
        'Triton LE', 'Ladder2019Season3\\TritonLE.SC2Map', [144, 144], [216, 216], '特里同 - 天梯版', '特里同-天梯版', 'TritonLE'
    ),
    'WintersGate': (
        "Winter's Gate LE", 'Ladder2019Season3\\WintersGateLE.SC2Map', [128, 132], [200, 176], '黑冬隘口 - 天梯版', '黑冬隘口-天梯版',
        'WintersGateLE'
    ),
    'WorldofSleepers': (
        'World of Sleepers LE', 'Ladder2019Season3\\WorldofSleepersLE.SC2Map', [144, 144], [184, 184], '梦境世界 - 天梯版',
        '梦境世界-天梯版', 'WorldofSleepersLE'
    ),
    'Flat32': (None, 'Melee\\Flat32.SC2Map', [28, 28], [32, 32], 'Simple Test Map 32x32', 'SimpleTestMap32x32', None),
    'Flat48': (None, 'Melee\\Flat48.SC2Map', [48, 48], [72, 80], 'Simple Test Map 48x48', 'SimpleTestMap48x48', None),
    'Flat64': (None, 'Melee\\Flat64.SC2Map', [64, 64], [88, 96], 'Simple Test Map 64x64', 'SimpleTestMap64x64', None),
    'Flat96': (None, 'Melee\\Flat96.SC2Map', [96, 96], [120, 128], 'Simple Test Map 96x96', 'SimpleTestMap96x96', None),
    'Flat128': (
        None, 'Melee\\Flat128.SC2Map', [128, 128], [152, 160], 'Simple Test Map 128x128', 'SimpleTestMap128x128', None
    ),
    'Simple64': (
        None, 'Melee\\Simple64.SC2Map', [64, 64], [88, 96], 'Simple Test Map 64x64', 'SimpleTestMap64x64', None
    ),
    'Simple96': (
        None, 'Melee\\Simple96.SC2Map', [96, 96], [120, 128], 'Simple Test Map 96x96', 'SimpleTestMap96x96', None
    ),
    'Simple128': (
        None, 'Melee\\Simple128.SC2Map', [128, 128], [152, 160], 'Simple Test Map 128x128', 'SimpleTestMap128x128', None
    ),
    'BuildMarines': (None, 'mini_games\\BuildMarines.SC2Map', [26, 18], [64, 64], 'MacroEconomy', 'MacroEconomy', None),
    'CollectMineralsAndGas': (
        None, 'mini_games\\CollectMineralsAndGas.SC2Map', [26, 18], [64, 64], 'MacroEconomy', 'MacroEconomy', None
    ),
    'CollectMineralShards': (
        None, 'mini_games\\CollectMineralShards.SC2Map', [22, 16], [64, 64], 'MovementBeaconUnselected',
        'MovementBeaconUnselected', None
    ),
    'DefeatRoaches': (None, 'mini_games\\DefeatRoaches.SC2Map', [22, 16], [64, 64], 'CombatFocus', 'CombatFocus', None),
    'DefeatZerglingsAndBanelings': (
        None, 'mini_games\\DefeatZerglingsAndBanelings.SC2Map', [22, 16], [64, 64], 'CombatFocus', 'CombatFocus', None
    ),
    'FindAndDefeatZerglings': (
        None, 'mini_games\\FindAndDefeatZerglings.SC2Map', [44, 32], [64, 64], 'CombatGroup', 'CombatGroup', None
    ),
    'MoveToBeacon': (None, 'mini_games\\MoveToBeacon.SC2Map', [22, 16], [64, 64], 'Movement01', 'Movement01', None),
}


def get_map_size(map_name, cropped=True):
    return MAPS[map_name][2 if cropped else 3]

# def get_localized_map_name(map_name, cleared=True):
#     return MAPS[map_name][5 if cleared else 4]

# def get_inverse_tran_table(table, indices):
#     inv_tab = {}
#     for k, v in table.items():
#         inv_tab[k] = k
#     for index in indices:
#         for k, v in table.items():
#             if v[index]:
#                 inv_tab[v[index]] = k
#     return inv_tab

# LOCALIZED_BNET_NAME_TO_PYSC2_NAME_LUT = get_inverse_tran_table(MAPS, [0, 4, 5, 6])
