# System configs
GLOBAL_HOST = '0.0.0.0'
LOCAL_HOST = '127.0.0.1'

# General request
DEFAULT_REQUEST_RETRIES = 5
DEFAULT_REQUEST_RETRY_WAITING = 1.0

# Slave configs
MIN_HEARTBEAT_SPAN = 0.2
DEFAULT_HEARTBEAT_SPAN = 3.0
DEFAULT_SLAVE_PORT = 7236

# Master configs
MIN_HEARTBEAT_CHECK_SPAN = 0.1
DEFAULT_HEARTBEAT_CHECK_SPAN = 1.0
DEFAULT_HEARTBEAT_TOLERANCE = 17.0
DEFAULT_MASTER_PORT = 7235

# Two-side configs
DEFAULT_CHANNEL = 0
