import pytest

from ...loader.number import interval


@pytest.mark.unittest
class TestConfigValidateNumber:
    def test_interval_common(self):
        _validator = interval(1, 3.5)
        assert not _validator(0.5)
        assert _validator(1.0)
        assert _validator(1.5)
        assert _validator(3.5)
        assert not _validator(4.0)

    def test_interval_all(self):
        _validator = interval()
        assert _validator(0.5)
        assert _validator(1.0)
        assert _validator(1.5)
        assert _validator(3.5)
        assert _validator(4.0)

    def test_interval_left_open(self):
        _validator = interval(1.0, left_ok=False)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert not _validator(0.999)
        assert not _validator(1.0)
        assert _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.5)
        assert _validator(4.0)

    def test_interval_left_open_eps(self):
        _validator = interval(1.0, left_ok=False, eps=0.01)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert not _validator(0.999)
        assert not _validator(1.0)
        assert not _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.5)
        assert _validator(4.0)

    def test_interval_left_close(self):
        _validator = interval(1.0)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert not _validator(0.999)
        assert _validator(1.0)
        assert _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.5)
        assert _validator(4.0)

    def test_interval_left_close_eps(self):
        _validator = interval(1.0, eps=0.01)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert _validator(0.999)
        assert _validator(1.0)
        assert _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.5)
        assert _validator(4.0)

    def test_interval_right_open(self):
        _validator = interval(right=3.5, right_ok=False)
        assert _validator(0.5)
        assert _validator(1.0)
        assert _validator(1.5)
        assert _validator(3.4)
        assert _validator(3.499)
        assert not _validator(3.5)
        assert not _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    def test_interval_right_open_eps(self):
        _validator = interval(right=3.5, right_ok=False, eps=0.01)
        assert _validator(0.5)
        assert _validator(1.0)
        assert _validator(1.5)
        assert _validator(3.4)
        assert not _validator(3.499)
        assert not _validator(3.5)
        assert not _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    def test_interval_right_close(self):
        _validator = interval(right=3.5)
        assert _validator(0.5)
        assert _validator(1.0)
        assert _validator(1.5)
        assert _validator(3.4)
        assert _validator(3.499)
        assert _validator(3.5)
        assert not _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    def test_interval_right_close_eps(self):
        _validator = interval(right=3.5, eps=0.01)
        assert _validator(0.5)
        assert _validator(1.0)
        assert _validator(1.5)
        assert _validator(3.4)
        assert _validator(3.499)
        assert _validator(3.5)
        assert _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    # noinspection DuplicatedCode
    def test_interval_both_open_open(self):
        _validator = interval(1.0, 3.5, left_ok=False, right_ok=False)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert not _validator(0.999)
        assert not _validator(1.0)
        assert _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.4)
        assert _validator(3.499)
        assert not _validator(3.5)
        assert not _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    # noinspection DuplicatedCode
    def test_interval_both_open_open_eps(self):
        _validator = interval(1.0, 3.5, left_ok=False, right_ok=False, eps=0.01)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert not _validator(0.999)
        assert not _validator(1.0)
        assert not _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.4)
        assert not _validator(3.499)
        assert not _validator(3.5)
        assert not _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    def test_interval_both_open_close(self):
        _validator = interval(1.0, 3.5, left_ok=False)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert not _validator(0.999)
        assert not _validator(1.0)
        assert _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.4)
        assert _validator(3.499)
        assert _validator(3.5)
        assert not _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    def test_interval_both_open_close_eps(self):
        _validator = interval(1.0, 3.5, left_ok=False, eps=0.01)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert not _validator(0.999)
        assert not _validator(1.0)
        assert not _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.4)
        assert _validator(3.499)
        assert _validator(3.5)
        assert _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    def test_interval_both_close_open(self):
        _validator = interval(1.0, 3.5, right_ok=False)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert not _validator(0.999)
        assert _validator(1.0)
        assert _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.4)
        assert _validator(3.499)
        assert not _validator(3.5)
        assert not _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    def test_interval_both_close_open_eps(self):
        _validator = interval(1.0, 3.5, right_ok=False, eps=0.01)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert _validator(0.999)
        assert _validator(1.0)
        assert _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.4)
        assert not _validator(3.499)
        assert not _validator(3.5)
        assert not _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    # noinspection DuplicatedCode
    def test_interval_both_close_close(self):
        _validator = interval(1.0, 3.5)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert not _validator(0.999)
        assert _validator(1.0)
        assert _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.4)
        assert _validator(3.499)
        assert _validator(3.5)
        assert not _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    def test_interval_both_close_close_eps(self):
        _validator = interval(1.0, 3.5, eps=0.01)
        assert not _validator(0.5)
        assert not _validator(0.9)
        assert _validator(0.999)
        assert _validator(1.0)
        assert _validator(1.001)
        assert _validator(1.1)
        assert _validator(1.5)
        assert _validator(3.4)
        assert _validator(3.499)
        assert _validator(3.5)
        assert _validator(3.501)
        assert not _validator(3.6)
        assert not _validator(4.0)

    def test_interval_invalid(self):
        with pytest.raises(ValueError):
            interval(1.0, 0.9)

    def test_interval_complex_1(self):
        _validator = float & (interval(1, 4, left_ok=False, right_ok=False) | interval(10.2, 13.4, eps=0.01))
        assert not _validator(0.9)
        assert not _validator(1.0)
        assert _validator(1.1)
        assert not _validator(2)
        assert _validator(2.0)
        assert _validator(3.9)
        assert not _validator(4.0)
        assert not _validator(4.1)
        assert not _validator(10.1)
        assert _validator(10.199)
        assert _validator(10.2)
        assert not _validator(11)
        assert _validator(11.0)
        assert _validator(13.4)
        assert _validator(13.401)
        assert not _validator(13.5)
        assert not _validator(None)
        assert not _validator('string')
