image: "registry.sensetime.com/xlab/sensestar-docker:centos7"

variables:
  CI: "true"

stages:
  - install
  - style
  - doc
  - test

install:
  stage: install
  script:
    - pip install -e .

style:
  stage: style
  script:
    - pip install yapf==0.29.0 flake8
    - make format_test flake_check

pages:
  stage: doc
  script:
    - pip install -e .
    - pip install sphinx sphinx_rtd_theme
    - make docs
    - mv nervex/docs/build/html public
    - rm -rf nervex/docs/build
  artifacts:
    paths:
      - public
  only:
    - master
    - /^doc/.*$/

test_unittest:
  stage: test
  tags:
    - nervex-gitlab-ci-runner-k8s
  variables:
    WORKERS: 8 # if you need to change to concurrency, just change here
  #    RANGE_DIR: ./nervex/xxxx # if you need to test some of the dirs, just change here
  script:
    - pip install -e .
    - make unittest

test_algotest:
  stage: test
  tags:
    - nervex-gitlab-ci-runner-k8s
  variables:
    DURATIONS: 10 # the count of durations
  #    RANGE_DIR: ./nervex/xxxx # if you need to test some of the dirs, just change here
  script:
    - pip install -e .
    - make algotest
  only:
    changes:
      - nervex/policy/*
      - nervex/model/*
      - nervex/rl_utils/*

test_benchmark:
  stage: test
  tags:
    - nervex-gitlab-ci-runner-k8s
  variables:
    WORKERS: 8 # if you need to change to concurrency, just change here
  #    RANGE_DIR: ./nervex/xxxx # if you need to test some of the dirs, just change here
  script:
    - pip install -e .
    - make benchmark

test_cudatest:
  stage: test
  tags:
    - nervex-gitlab-ci-runner-k8s
  variables:
    KUBERNETES_RESOURCES_LIMITS_NVIDIA.COM/GPU: "8"
    KUBERNETES_RESOURCES_REQUESTS_NVIDIA.COM/GPU: "8"
  image: "registry.sensetime.com/xlab/sensestar-docker:cuda9-centos7"
  script:
    - yum -y install gcc automake autoconf libtool libsm6 make
    - pip install -e .
    - make cudatest
