image: "registry.sensetime.com/xlab/sensestar-docker:centos7"
stages:
  - install
  - style
  - doc
  - test

install:
  stage: install
  script:
    - pip install -e .

style:
  stage: style
  script:
    - pip install yapf==0.29.0
    - bash format.sh --test
    - pip install flake8
    - flake8 nervex/

pages:
  stage: doc
  script:
  - pip install -e .
  - pip install sphinx sphinx_rtd_theme
  - cd nervex/docs
  - make html
  - mv build/html ../../public
  - rm -r build
  artifacts:
    paths:
    - public

test:
  stage: test
  script:
    - pip install -e .
    - coverage run --branch --source=./nervex -m pytest nervex/ -n 4 -sv -m unittest
    - coverage report --show-missing
