image: "registry.sensetime.com/xlab/sensestar-docker:centos7"
stages:
  - install
  - style
  - doc
  - test

install:
  stage: install
  script:
    - pip install -e .

style:
  stage: style
  script:
    - pip install yapf==0.29.0
    - bash format.sh --test
    - pip install flake8
    - flake8 nervex/

pages:
  stage: doc
  script:
    - pip install -e .
    - pip install sphinx sphinx_rtd_theme
    - cd nervex/docs
    - make html
    - mv build/html ../../public
    - rm -r build
  artifacts:
    paths:
      - public
  only:
    - master

test:
  stage: test
  script:
    - pip install -e .
    - pytest ./nervex ./app_zoo --cov-report term-missing --cov=./nervex -n 4 -sv -m unittest
