image: "registry.sensetime.com/spring/dka:pytorch0.4.1"
stages:
  - style
  - test
  - deploy

style:
  stage: style
  script:
    - pip install yapf==0.29.0
    - bash format.sh --test
    - pip install flake8
    - flake8 sc2learner/

test:
  stage: test
  script:
    - pip install -e .
    - pytest sc2learner/data/tests/ -sv 

pages:
  stage: deploy
  script:
  - pip install sphinx sphinx_rtd_theme
  - cd sc2learner/docs
  - PYTHONPATH=../patches:$PYTHONPATH make html
  - mv build/html ../../public
  - rm -r build
  artifacts:
    paths:
    - public
  only:
    - nyz-dev
