image: "registry.sensetime.com/xlab/sensestar-docker:centos7"

variables:
  CI: "true"

stages:
  - install
  - style
  - doc
  - test

install:
  stage: install
  script:
    - pip install -e .

style:
  stage: style
  script:
    - pip install yapf==0.29.0 flake8
    - make format_test flake_check

pages:
  stage: doc
  script:
    - pip install -e .
    - pip install sphinx sphinx_rtd_theme
    - make docs
    - mv nervex/docs/build/html public
    - rm -rf nervex/docs/build
  artifacts:
    paths:
      - public
  only:
    - master

test_unittest:
  stage: test
  variables:
    WORKERS: 8 # if you need to change to concurrency, just change here
  #    RANGE_DIR: ./nervex/xxxx # if you need to test some of the dirs, just change here
  script:
    - pip install -e .
    - make unittest

test_algotest:
  stage: test
    variables:
      WORKERS: 8 # if you need to change to concurrency, just change here
      DURATIONS: 10 # the count of durations
    #    RANGE_DIR: ./nervex/xxxx # if you need to test some of the dirs, just change here
    script:
      - pip install -e .
      - make algotest

test_benchmark:
  stage: test
    variables:
      WORKERS: 8 # if you need to change to concurrency, just change here
    #    RANGE_DIR: ./nervex/xxxx # if you need to test some of the dirs, just change here
    script:
      - pip install -e .
      - make benchmark