image: "registry.sensetime.com/xlab/sensestar-docker:centos7"

variables:
  CI: "true"

stages:
  - install
  - style
  - doc
  - test

install:
  stage: install
  script:
    - pip install -e .

style:
  stage: style
  script:
    - pip install yapf==0.29.0 flake8
    - make format_test flake_check

pages:
  stage: doc
  script:
    - pip install -e .
    - pip install sphinx sphinx_rtd_theme
    - make docs
    - mv nervex/docs/build/html public
    - rm -rf nervex/docs/build
  artifacts:
    paths:
      - public
  only:
    - master

test:
  stage: test
  script:
    - pip install -e .
    - pytest ./nervex --cov-report term-missing --cov=./nervex -n 12 -sv -m unittest
