image: "registry.sensetime.com/xlab/sensestar-docker:centos7"
stages:
  - style
  - doc
  - test

style:
  stage: style
  script:
    - pip install yapf==0.29.0
    - bash format.sh --test
    - pip install flake8
    - flake8 sc2learner/

pages:
  stage: doc
  script:
  - pip install sphinx sphinx_rtd_theme
  - cd sc2learner/docs
  - make html
  - mv build/html ../../public
  - rm -r build
  artifacts:
    paths:
    - public

test:
  stage: test
  script:
    - pip install -e .
    - pytest sc2learner/ -n 4 -sv -m unittest 
