FROM opendilab/ding:nightly as atari

WORKDIR /ding

RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install --no-cache-dir .[common_env] \
    && pip install autorom \
    && AutoROM --accept-license

FROM opendilab/ding:nightly as mujoco

WORKDIR /ding

RUN python3 -m pip install --upgrade pip \
    && curl https://www.roboti.us/mjkey.txt -o mjkey.txt && curl https://www.roboti.us/download/mujoco200_linux.zip -o mujoco200_linux.zip \
    && apt-get install unzip libgl1-mesa-dev && unzip mujoco200_linux.zip && mv mujoco200_linux mujoco200 \
    && export MUJOCO_PY_MJKEY_PATH=/ding/mjkey.txt && export MUJOCO_PY_MUJOCO_PATH=/ding/mujoco200 && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/ding/mujoco200/bin \
    && pip3 install -U 'mujoco-py<2.1,>=2.0'
