league:
    league_type: 'static'
    import_names: []  # placeholder
    # ---player----
    player_category: ['zerg']  # placeholder
    active_players: 
        main_player: 1
    main_player:
        branch_probs:
            pfsp: 0.5
            sp: 0.35
            verification: 0.15
        strong_win_rate: 0.7
        one_phase_steps: 2e3
    use_pretrain_init_historical: True
    pretrain_checkpoint_path:  # placeholder
        zerg: 'pretrain_checkpoint_zerg.pth'
    # ---payoff---
    payoff:
        type: 'solo'  # ['solo', 'battle']
        buffer_size: 100
        decay: 0.99
        min_win_rate_games: 8
    # ---runner---
    max_active_player_task: 3
    #per_match_games: 8
    time_interval: 1
    task:
        env_num: 8
        episode_num: 2
        data_push_length: 128
        agent_update_freq: 30  # second
        compressor: 'none'
model:
    placeholder:
