league:
    league_type: 'base'
    import_names: [nervex.league]
    # ---player----
    player_category: ['solo']
    active_players: 
        solo_active_player: 1
    use_pretrain_init_historical: False
    pretrain_checkpoint_path:
        solo: 'pretrain_checkpoint_solo.pth'
    # ---payoff---
    payoff:
        type: 'solo'  # ['solo', 'battle']
        buffer_size: 100
    # ---runner---
    max_active_player_job: 3
    time_interval: 1
