api:
    learner_port: 18293               # learner port
    coordinator_ip: 10.198.6.31       # learner and coordinator are in same cluster
    coordinator_port: 18294
    manager_ip: 10.198.6.31           # could be all cluster
    manager_port: 18295
    ceph_path: s3://alphastar_fake_data/
    actor:
        heartbeats_thread: True
    manager:
        auto_run_actor: False
        use_partitions: ['VI_SP_Y_V100_A', 'VI_SP_Y_V100_B']
        actor_num: [2, 2]
    coordinator:
        use_fake_data: True
        fake_model_path: iterations_2200.pth.tar
        fake_stat_path: Zerg_Zerg_6280_d35c22b2d7e462f1481621cbf765709961e3f9a2a99f8f6c6fa814ccffc831d6.stat_processed
replay_buffer:
    meta_maxlen: 4096
    max_reuse: 2
    min_sample_ratio: 2
    alpha: 0.6
    beta: 0.5
    cache_maxlen: 256
    timeout: 8  # times of the seconds of per learning iteration
