common:
    name: CartpoleDqnConfig
    time_wrapper_type: cuda
    save_path: '.'
    load_path: ''
learner:
    use_cuda: False
    use_distributed: False
    max_iterations: 10000000
    train_step: 200
    batch_size: 64
    learning_rate: 0.0001
    weight_decay: 0.0
    data:
        max_reuse: 100
        buffer_length: 10000
    dqn:
        discount_factor: 0.99
        is_double: True
        dueling: True
    hook:
        save_ckpt_after_iter:
            name: save_ckpt_after_iter
            type: save_ckpt
            priority: 40
            position: after_iter
            ext_args:
                freq: 1000
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 100
env:
    env_num: 8
    stop_val: 195
actor:
    episode_num: 2 
    eval_step: 100
