common:
    name: PongDQNConfig
    save_path: '.'
    load_path: ''
env:
    env_manager_type: 'subprocess'  # [base, subprocess]
    import_names: [ 'app_zoo.atari.envs.atari_env' ]
    env_type: 'atari'
    env_id: 'PongNoFrameskip-v4'
    frame_stack: 4
    is_train: True
    actor_env_num: 16
    evaluator_env_num: 3
policy:
    use_cuda: True
    policy_type: 'dqn'
    import_names: [ 'nervex.policy.dqn' ]
    on_policy: False
    model:
        encoder_kwargs:
            encoder_type: 'conv2d'
        obs_dim: [ 4, 84, 84 ]
        action_dim: 6
        embedding_dim: 512
        head_kwargs:
            dueling: False
    learn:
        train_step: 20
        batch_size: 32
        learning_rate: 0.0001
        weight_decay: 0.0
        algo:
            target_update_freq: 500
            discount_factor: 0.99
            nstep: 3
    collect:
        traj_len: 11
        unroll_len: 1
        algo:
            nstep: 3
    command:
        eps:
            type: 'linear'
            start: 1.
            end: 0.05
            decay: 200000
replay_buffer:
    meta_maxlen: 10000
    max_reuse: 100
    unroll_len: 1
    min_sample_ratio: 1
actor:
    n_sample: 100
    traj_len: 11
    traj_print_freq: 100
    collect_print_freq: 100
evaluator:
    n_episode: 4
    eval_freq: 5000
    stop_val: 20 # pong
learner:
    hook:
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 100
command:
    placeholder: 'placeholder'
