apiVersion: nervex.sensetime.com/v1alpha1
kind: NerveXJob
metadata:
  name: nervexjob-example
spec:
  group: xxx
  priorityClassName: ""
  cleanPodPolicy: "Running"
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory
      sizeLimit: 128Mi
  - name: work-dir
    hostPath:
      path: /data/nfs/nervex/cartpole
  coordinator:
    template:
      spec:
        containers:
        - name: coordinator
          image: registry.sensetime.com/cloudnative4ai/nervex:v0.0.5-torch1.8.1-cuda11.1-cudnn8-runtime-24bd5271
          imagePullPolicy: Always
          env:
          - name: LC_ALL
            value: "en_US.utf-8"
          - name: LANG
            value: "en_US.utf-8"
          - name: PYTHONUNBUFFERED
            value: "1"
          resources:
            requests:
              cpu: 3
              memory: "10Gi"
            limits:
              cpu: 3
              memory: "10Gi"
          command: ["/bin/bash", "-c",]
          args:
          - |
            nervex -m dist --module config -p k8s -c app_zoo/classic_control/cartpole/config/parallel/cartpole_dqn_config_k8s.py -s 0;
            nervex -m dist --module coordinator -p k8s -c app_zoo/classic_control/cartpole/config/parallel/cartpole_dqn_config_k8s.py.pkl -s 0 --disable_flask_log 0 -cdp $COORDINATOR_PORT
          ports:
          - name: coordinator
            containerPort: 22270
          volumeMounts:
          - name: work-dir
            mountPath: /nervex
  collector:
    template:
      spec:
        containers:
        - name: collector
          image: registry.sensetime.com/cloudnative4ai/nervex:v0.0.5-torch1.8.1-cuda11.1-cudnn8-runtime-24bd5271
          imagePullPolicy: Always
          env:
          - name: LC_ALL
            value: "en_US.utf-8"
          - name: LANG
            value: "en_US.utf-8"
          - name: PYTHONUNBUFFERED
            value: "1"
          resources:
            requests:
              cpu: 3
              memory: "10Gi"
            limits:
              cpu: 3
              memory: "10Gi"
          command: ["/bin/bash", "-c",]
          args:
          - |
            nervex -m dist --module collector -c app_zoo/classic_control/cartpole/config/parallel/cartpole_dqn_config_k8s.py.pkl -s 0 -clp $COLLECTOR_PORT
          ports:
          - name: collector
            containerPort: 22270
          volumeMounts:
          - name: work-dir
            mountPath: /nervex
  learner:
    template:
      spec:
        containers:
        - name: learner
          image: registry.sensetime.com/cloudnative4ai/nervex:v0.0.5-torch1.8.1-cuda11.1-cudnn8-runtime-24bd5271
          imagePullPolicy: Always
          env:
          - name: LC_ALL
            value: "en_US.utf-8"
          - name: LANG
            value: "en_US.utf-8"
          - name: PYTHONUNBUFFERED
            value: "1"
          resources:
            requests:
              cpu: 3
              memory: "20Gi"
            limits:
              cpu: 3
              memory: "20Gi"
          command: ["/bin/bash", "-c",]
          args:
          - |
            nervex -m dist --module spawn_learner -c app_zoo/classic_control/cartpole/config/parallel/cartpole_dqn_config_k8s.py.pkl -s 0 -lp $LEARNER_PORT
          ports:
          - name: learner
            containerPort: 22270
          volumeMounts:
          - name: cache-volume
            mountPath: /dev/shm
          - name: work-dir
            mountPath: /nervex
