common:
    name: BitFlipHerConfig
    save_path: '.'
    load_path: ''
env:
    env_manager_type: 'base'  # [base, subprocess]
    import_names: ['app_zoo.classic_control.bitflip.envs.bitflip_env']
    env_type: 'bitflip'
    actor_env_num: 1
    evaluator_env_num: 8
    n_bits: 5
policy:
    use_cuda: False
    policy_type: 'dqn'
    import_names: ['nervex.policy.dqn']
    on_policy: False
    model:
        obs_dim: 10
        action_dim: 5
        embedding_dim: 64
        dueling: False
    learn:
        train_step: 1
        batch_size: 32
        learning_rate: 0.0001
        weight_decay: 0
        algo:
            nstep: 1
            target_update_freq: 500
            discount_factor: 0.9
    collect:
        traj_len: 50
        unroll_len: 1
        algo:
            nstep: 1
            use_her: True
            her_strategy: 'final'
            her_replay_k: 1
    command:
        eps:
            type: 'exp'
            start: 0.95
            end: 0.02
            decay: 10000
replay_buffer:
    meta_maxlen: 5000
    unroll_len: 1
    agent:
        min_sample_ratio: 5
        max_reuse: 100
actor:
    n_episode: 1
    traj_len: 50
    traj_print_freq: 100
    collect_print_freq: 100
evaluator:
    n_episode: 16
    eval_freq: 100
    stop_val: 0.9
learner:
    hook:
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 100
commander:
    placeholder: 'placeholder'