FROM opendilab/ding:nightly as atari

WORKDIR /ding

RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install --no-cache-dir .[common_env] \
    && pip install autorom \
    && AutoROM --accept-license

FROM opendilab/ding:nightly as mujoco

WORKDIR /ding

RUN apt update \
    && apt install -y \
    build-essential \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libosmesa6-dev \
    libglfw3 \
    libglfw3-dev \
    libsdl2-dev \
    libsdl2-image-dev \
    libglm-dev \
    libfreetype6-dev \
    patchelf

RUN mkdir -p /root/.mujoco \
    && wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -O mujoco.tar.gz \
    && tar -xf mujoco.tar.gz -C /root/.mujoco \
    && rm mujoco.tar.gz \
    && echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mjpro210/bin:/root/.mujoco/mujoco210/bin" >> /root/.bashrc

ENV LD_LIBRARY_PATH /root/.mujoco/mjpro210/bin:/root/.mujoco/mujoco210/bin:${LD_LIBRARY_PATH}

Run python3 -m pip install --upgrade pip \
    && pip3 install numpy \
    && pip3 install -U 'mujoco-py<2.2,>=2.1' --user

RUN pip3 install -U "gym[all]" --user

FROM opendilab/di-star:latest as smac

WORKDIR /ding

ADD setup.py setup.py
ADD dizoo dizoo
ADD ding ding
ADD README.md README.md

RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install --no-cache-dir .[fast]

ENV SC2PATH=/root/StarCraftII_4.10.0

FROM opendilab/ding:nightly as grf

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /ding

RUN apt-get update && apt-get install git cmake build-essential libgl1-mesa-dev libsdl2-dev \
    libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev \
    libdirectfb-dev libst-dev mesa-utils xvfb x11vnc -y \
    && apt clean \
    && rm -rf /var/cache/apt/*

RUN python3 -m pip install --upgrade pip setuptools psutil wheel \
    && python3 -m pip install --no-cache-dir gfootball

FROM opendilab/ding:nightly as dmc2gym

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /ding

RUN apt-get update && apt-get install glew-utils freeglut3 freeglut3-dev libosmesa6 wget zip ffmpeg -y

ENV MUJOCO_GL "egl"

RUN wget https://codeload.github.com/denisyarats/dmc2gym/zip/refs/heads/master -O dmc2gym-master.zip \
    && unzip dmc2gym-master.zip \
    && python3 -m pip install --no-cache-dir ./dmc2gym-master/ \
    && rm -rf dmc2gym-master \
    && rm dmc2gym-master.zip

FROM opendilab/ding:nightly-mujoco as metaworld

WORKDIR /ding

RUN mkdir tempfile \
	&& cd tempfile \
	&& wget https://github.com/rlworkgroup/metaworld/archive/refs/heads/master.zip -O metaworld_master.zip \
    && apt-get install unzip \
	&& unzip metaworld_master.zip \
    && python3 -m pip install --no-cache-dir ./metaworld-master/ \
	&& cd .. \
    && rm -rf tempfile

FROM opendilab/ding:nightly as cityflow

WORKDIR /ding

RUN apt update \
    && apt install -y \
    build-essential \
    cmake

RUN mkdir -p /root/.cityflow \
    && cd /root/.cityflow \
    && git clone https://github.com/cityflow-project/CityFlow \
    && cd CityFlow \
    && pip install -e .

RUN mkdir -p /root/.smartcross \
    && cd /root/.smartcross \
    && git clone https://github.com/opendilab/DI-smartcross \
    && cd DI-smartcross \
    && pip install -e .
 
