FROM opendilab/ding:nightly as atari

WORKDIR /ding

RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install --no-cache-dir .[common_env] \
    && pip install autorom \
    && AutoROM --accept-license

FROM opendilab/ding:nightly as mujoco

WORKDIR /ding

RUN apt update \
    && apt install -y \
    build-essential \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libosmesa6-dev \
    libglfw3 \
    libglfw3-dev \
    libsdl2-dev \
    libsdl2-image-dev \
    libglm-dev \
    libfreetype6-dev \
    patchelf

RUN mkdir -p /root/.mujoco \
    && wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -O mujoco.tar.gz \
    && tar -xf mujoco.tar.gz -C /root/.mujoco \
    && rm mujoco.tar.gz \
    && echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mjpro210/bin:/root/.mujoco/mujoco210/bin" >> /root/.bashrc

ENV LD_LIBRARY_PATH /root/.mujoco/mjpro210/bin:/root/.mujoco/mujoco210/bin:${LD_LIBRARY_PATH}

Run python3 -m pip install --upgrade pip \
    && pip3 install "cython<3" \
    && pip3 install --no-cache-dir numpy \
    && pip3 install --no-cache-dir -U "gym[mujoco,mujoco_py]==0.25.1" --user \
    && pip install gymnasium[mujoco] \
    && python -c "import mujoco_py"

FROM opendilab/di-star:latest as smac

WORKDIR /ding

ADD setup.py setup.py
ADD dizoo dizoo
ADD ding ding
ADD README.md README.md

RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install --no-cache-dir .[fast]

ENV SC2PATH=/root/StarCraftII_4.10.0

FROM opendilab/ding:nightly as grf

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /ding

RUN apt-get update && apt-get install git build-essential libgl1-mesa-dev libsdl2-dev \
    libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev \
    libdirectfb-dev libst-dev mesa-utils xvfb x11vnc -y \
    && apt clean \
    && rm -rf /var/cache/apt/*

RUN python3 -m pip install --upgrade pip setuptools psutil wheel \
    && python3 -m pip install --no-cache-dir gfootball

FROM opendilab/ding:nightly as dmc2gym

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /ding

RUN apt-get update && apt-get install glew-utils freeglut3 freeglut3-dev libosmesa6 wget zip ffmpeg -y

ENV MUJOCO_GL "egl"

RUN wget https://codeload.github.com/denisyarats/dmc2gym/zip/refs/heads/master -O dmc2gym-master.zip \
    && unzip dmc2gym-master.zip \
    && python3 -m pip install --no-cache-dir ./dmc2gym-master/ \
    && rm -rf dmc2gym-master \
    && rm dmc2gym-master.zip

FROM opendilab/ding:nightly-mujoco as metaworld

WORKDIR /ding

RUN mkdir tempfile \
    && cd tempfile \
    && python3 -m pip install --no-cache-dir git+https://github.com/Farama-Foundation/Metaworld.git@b2a4cbb98e20081412cb4cc7ae3d4afc456a732a \
    && cd .. \
    && rm -rf tempfile

RUN apt-get install xvfb ffmpeg -y \
    && rm -rf /opt/conda/bin/ffmpeg \
    && ln -s /usr/bin/ffmpeg /opt/conda/bin/ffmpeg

FROM opendilab/ding:nightly as cityflow

WORKDIR /ding

RUN apt update \
    && apt install -y \
    build-essential

RUN mkdir -p /root/.cityflow \
    && cd /root/.cityflow \
    && git clone https://github.com/cityflow-project/CityFlow \
    && cd CityFlow \
    && pip install -e .

RUN mkdir -p /root/.smartcross \
    && cd /root/.smartcross \
    && git clone https://github.com/opendilab/DI-smartcross \
    && cd DI-smartcross \
    && pip install -e .


FROM opendilab/ding:nightly as evogym

WORKDIR /ding

RUN apt update \
    && apt install -y \
    build-essential libglew-dev libglu1-mesa-dev xorg-dev

RUN mkdir -p /root/.evogym \
    && cd /root/.evogym \
    && git clone --recurse-submodules https://github.com/PaParaZz1/evogym.git \
    && cd evogym \
    && pip3 install -r requirements.txt

RUN cd /root/.evogym/evogym && python3 setup.py install

FROM opendilab/ding:nightly-mujoco as d4rl

WORKDIR /ding

RUN git clone https://github.com/PaParaZz1/D4RL.git 

RUN cd D4RL \
    && pip install -e .
