common:
    name: AtariConfig
    save_path: '.'
    load_path: ''
env:
    env_manager_type: 'subprocess'  # [base, subprocess]
    import_names: [ 'app_zoo.atari.envs.atari_env' ]
    env_type: 'atari'
    env_id: 'PongNoFrameskip-v4'
    frame_stack: 4
    is_train: True
    actor_env_num: 16
    evaluator_env_num: 8
policy:
    use_cuda: True
    policy_type: 'a2c'
    import_names: ['nervex.policy.a2c']
    on_policy: True
    model_type: 'ConvValueAC'
    model:
        obs_dim: [4, 84, 84 ]
        action_dim: 6
        embedding_dim: 128
    learn:
        train_step: 1
        batch_size: 80
        learning_rate: 0.0001
        weight_decay: 0.0
        algo:
            value_weight:  0.5
            entropy_weight: 0.01
    collect:
        traj_len: 6
        unroll_len: 1
        algo:
            gae_lambda: 0.99
            discount_factor: 0.99

    command:
        placeholder: 'placeholder'

replay_buffer:
    meta_maxlen: 10000
    max_reuse: 1
    unroll_len: 1
    min_sample_ratio: 1
actor:
    n_sample: 80
    traj_len: 6
    traj_print_freq: 1000
    collect_print_freq: 1000
evaluator:
    n_episode: 8
    eval_freq: 10000
    stop_val: 20
learner:
    hook:
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 10000
command:
    placeholder: 'placeholder'
