common:
    name: QbertDqnTestConfig
    save_path: '.'
    load_path: ''
env:
    env_manager_type: 'base'  # [base, subprocess]
    import_names: ['app_zoo.atari.envs.atari_env']
    env_type: 'atari'
    actor_env_num: 16
    evaluator_env_num: 10
    env_id: 'QbertNoFrameskip-v4'
    frame_stack: 4
    is_train: True
policy:
    use_cuda: True
    policy_type: 'dqn'
    import_names: ['nervex.policy.dqn']
    on_policy: False
    model:
        encoder_kwargs:
          encoder_type: 'conv2d'
        obs_dim: [4, 84, 84]
        action_dim: 6
        embedding_dim: 512
        dueling: True
    learn:
        train_step: 100
        batch_size: 32
        learning_rate: 0.0001
        weight_decay: 0.0
        algo:
            target_update_freq: 500
            discount_factor: 0.99
            nstep: 3
    collect:
        traj_len: 11
        unroll_len: 1
        algo:
            nstep: 3
    command:
        eps:
            type: 'linear'
            start: 1.0
            end: 0.05
            decay: 100000
replay_buffer:
    meta_maxlen: 100000
    max_reuse: 100
    unroll_len: 1
    min_sample_ratio: 1
actor:
    n_sample: 1000
    traj_len: 11
    traj_print_freq: 100
    collect_print_freq: 100
evaluator:
    n_episode: 1
    eval_freq: 200
    stop_val: 5000
learner:
    hook:
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 100
command:
    placeholder: 'placeholder'
