common:
    name: SumoDqnDistConfig
    time_wrapper_type: cuda
    save_path: '.'
    load_path: ''
replay_buffer:
    meta_maxlen: 10000
    max_reuse: 8
    min_sample_ratio: 1
    unroll_len: 1
    enable_track_used_data: True
learner:
    learner_type: 'sumo_dqn'
    import_names: ['app_zoo.sumo.worker.learner.sumo_dqn_learner']
    use_cuda: False
    use_distributed: False
    max_iterations: 10000000
    train_step: 200
    batch_size: 8
    unroll_len: 1
    learning_rate: 0.001
    weight_decay: 0.0001
    reward_weights:
        'queue_len': 1.0
    dqn:
        discount_factor: 0.95
        is_double: True
        dueling: True
    hook:
        save_ckpt_after_iter:
            name: save_ckpt_after_iter
            type: save_ckpt
            priority: 40
            position: after_iter
            ext_args:
                freq: 500
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 1
    communication:
        type: 'flask_fs'
        upstream_ip: '127.0.0.1'
        upstream_port: 13297
        learner_ip: 127.0.0.1
        learner_port: 13295
        heartbeats_freq: 50
        send_agent_freq: 10
        send_train_info_freq: 10
        path_traj: '.'
        path_agent: '.'
        restore: False
env:
    env_num: 4
    env_type: 'fake'  # ['normal', 'fake']
    stop_val: -2000
actor:
    actor_type: 'sumowj3'
    import_names: ['app_zoo.sumo.worker.actor.sumowj3_actor_controller']
    use_cuda: False
    print_freq: 100
    episode_num: 4
    communication:
        type: flask_fs  # ['single_machine', 'flask_fs']
        path_agent: '.'
        path_traj: '.'
        heartbeats_freq: 30
        upstream_ip: '127.0.0.1'
        upstream_port: 13296
league:
    league_type: 'static'
    import_names: ['nervex.league.static_league_manager']
    use_pretrain_init_historical: False
    player_category: ['main']
    pretrain_checkpoint_path:
        main: 'main_ckpt.pth'
    task:
        data_push_length: 64
    communication:
        type: 'flask_fs'
        file_system_type: 'normal'  # ['normal', 'ceph']
        path_agent: '.'
        path_traj: '.'
system:
    manager_ip: '127.0.0.1'
    manager_port: 13296
    coordinator_ip: '127.0.0.1'
    coordinator_port: 13297
    resume_dir: '.'
    manager_resume_path:
    coordinator_resume_path:
    coordinator_check_dead_learner_freq: 300
    league_manager_ip: '127.0.0.1'
    league_manager_port: 13298
    actor_num: 2
