@startuml serial_evaluator
start
#orange:serial_controller init, set env_manager and eval_mode policy;
#pink:env reset;
repeat
  #orange:policy data_preprocess;
  #orange:policy forward_with_obs;
  #orange:policy data_postprocess;
  #pink:env step_with_action;
  if (for every env: env i is done?) then (yes)
    #pink:env reset_i;
    #orange:policy eval_mode_reset;
    :evaluator log_episode_result;
  endif
  :evaluator log_statistics_data;
repeat while (eval episodes are not enough?)
:evaluator get_average_episode_result;
stop
@enduml
