@startuml serial_actor
header Serial Pipeline
title Serial Actor

|#green|serial_controller|
|#pink|env_manager|
|#orange|policy|
|actor|

|#green|serial_controller|
start
:init actor, set its \nenv_manager and \ncollect_mode policy;
|#pink|env_manager|
:env reset;
repeat
  |#orange|policy|
  :policy data_preprocess;
  :policy forward with obs;
  :policy data_postprocess;
  |#pink|env_manager|
  :env step with action;
  |#orange|policy|
  :policy process_transition;
  |actor|
  :actor save transition in cache;
  if (for every env: \n - env i is done? <b>OR</b> \n - cache length is not smaller than traj_len?) then (yes)
    |#orange|policy|
    :policy get_train_sample from cache;
    |actor|
    :actor save train_sample for return;
    if (env i is done?) then (yes)
      |#pink|env_manager|
      :env i reset;
      |#orange|policy|
      :policy collect_mode reset;
      |actor|
      :actor log episode_collect_info;
    endif
  endif
repeat while (generated traj data is not enough?)
|actor|
:actor log statistics;
:actor return collect_data and collect_info;
stop

@enduml
