@startuml serial_learner
start
#orange:serial_controller init and set learn_mode policy;
repeat
  :learner call before_iter hook;
  #orange:policy data_preprocess;
  #orange:policy forward(including backward and grad update);
  :learner update log_buffer info and priority info;
  :learner update_info_to_controller;
repeat while (train iteration is not enough?)
stop
@enduml
