common:
    name: SumoDqnConfig
    save_path: '.'
    load_path: ''
env:
    env_manager_type: 'subprocess'  # [base, subprocess]
    import_names: ['app_zoo.sumo.envs.sumo_env', 'app_zoo.sumo.envs.fake_sumo_env']
    env_type: 'sumo_wj3'
    actor_env_num: 16
    evaluator_env_num: 2
policy:
    use_cuda: False
    policy_type: 'sumo_dqn'
    import_names: ['app_zoo.sumo.policy.sumo_dqn']
    on_policy: False
    model:
        obs_dim: 380
        action_dim: [2, 2, 3]
        embedding_dim: 128
        dueling: True
    learn:
        batch_size: 64
        learning_rate: 0.001
        weight_decay: 0.0001
        algo:
            target_update_freq: 500
            discount_factor: 0.95
    collect:
        get_traj_length: 1
    command:
        eps:
            type: 'exp'
            start: 0.95
            end: 0.05
            decay: 100000
replay_buffer:
    meta_maxlen: 100000
    max_reuse: 8
    unroll_len: 1
    min_sample_ratio: 1
actor:
    n_step: 16
    traj_print_freq: 500
    collect_print_freq: 500
evaluator:
    n_episode: 2
    eval_freq: 1000
    stop_val: 0
learner:
    hook:
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 500
command:
    placehoolder: 'placehoolder'
