common:
    name: AlphastarRL
    time_wrapper_type: cuda
    save_path: '.'
    load_path: ''
    only_evaluate: False
# for testing actor worker
actor:
    heartbeats_thread: True
    heartbeats_freq: 10
    max_connection_retries: 20
coordinator:
    use_fake_data: True
    fake_model_path: iterations_2200.pth.tar
    fake_stat_path: Zerg_Zerg_6280_d35c22b2d7e462f1481621cbf765709961e3f9a2a99f8f6c6fa814ccffc831d6.stat_processed
# values in this section is mean to be shared by multiple components
system:
    learner_port: 18293               # learner port
    coordinator_ip: 10.198.6.31       # learner and coordinator are in same cluster
    coordinator_port: 18294
    # manager_ip can be set to 'auto' or the real IP of the manager instance
    # this value is used by actors to find what they should connect and report to
    # if it's set to 'auto', the manager node of the Slurm cluster will be used as the manager
    manager_ip: 'auto'
    manager_port: 18295
    auto_run_actor: False
    use_partitions: ['VI_SP_Y_V100_A', 'VI_SP_Y_V100_B']
    actor_num: [2, 2]
    use_ceph: False  # TODO: there is no support for lustre file on the actor side
    # The paths must end with a /
    ceph_traj_path: 's3://alphastar_fake_data/'
    ceph_model_path: 's3://alphastar_fake_data/'
    ceph_stat_path: 's3://alphastar_fake_data/'
replay_buffer:
    meta_maxlen: 4096
    max_reuse: 2
    min_sample_ratio: 2
    alpha: 0.6
    beta: 0.5
    cache_maxlen: 16
    timeout: 8  # times of the seconds of per learning iteration
data:
    train:
        batch_size: 2
        dataloader_type: 'online'
train:
    use_cuda: False
    use_distributed: False
    max_iterations: 10
    batch_size: 2
    trajectory_len: 3
model:
    use_value_network: True
logger:
    print_freq: 1
    save_freq: 200
    eval_freq: 200
    var_record_type: 'alphastar'
