# This file provide configs for "data" and "train" fields, both top-level fields.

# ===== Supervised Learning Data Setting =====
data:
    train:
        replay_list: ''
        dataset_type: replay
        dataloader_type: iter  # [epoch, iter]
        batch_size: 6
        trajectory_len: 48
        trajectory_type: sequential  # [epoch: [slide_window], iter: [sequential]]
        slide_window_step: 48
        beginning_build_order_prob: 0.8
        use_stat: True
        beginning_build_order_num: 20
        use_global_cumulative_stat: False
        cumulative_stat_prob: 0.5
        use_ceph: True
        use_distributed: False
        use_available_action_transform: True
        use_enemy_upgrades: True
    eval:
        replay_list: ''
        dataset_type: replay_eval
        dataloader_type: epoch
        batch_size: 1
        use_stat: True
        beginning_build_order_num: 20
        use_global_cumulative_stat: False
        use_ceph: True
        use_distributed: False
        use_available_action_transform: True
        use_enemy_upgrades: True

# ===== Supervised Learning Training Setting =====
train:
    use_cuda: True
    max_epochs: 1000
    learning_rate: 1e-3
    weight_decay: 1e-5
    temperature: 1.0
    criterion:
        type: cross_entropy  # [cross_entropy, label_smooth_ce]
        kwargs:  # {label_smooth_ce: [smooth_ratio]}
            smooth_ratio: 0.1
        action_type: normal  # [normal, double_head]
    parallel: True
