@startuml
participant "Master End" as master
participant "Slave End" as slave

group Launching
    master -> slave : Connect to slave end
    return Connection established
end

group Running
    master -> slave : Send task to slave end
    return Task received

    slave -> master : Send result to master end (success or failure)
    return Result received
end

group Shutting down
    master -> slave : Disconnect from slave end
    return Connection down
end

@enduml