from .coinrun_dqn_default_config import coinrun_dqn_default_config
from .coinrun_ppo_default_config import coinrun_ppo_default_config
from .coinrun_ppg_default_config import coinrun_ppg_default_config