common:
    name: CooperativeNavigationQMIXConfig
    save_path: '.'
    load_path: ''
env:
    env_manager_type: 'subprocess'  # [base, subprocess]
    import_names: ['app_zoo.multiagent_particle.envs.particle_env']
    env_type: 'cooperative_navigation'
    num_agents: 5
    num_landmarks: 6
    agent_num: 5
    actor_env_num: 8
    evaluator_env_num: 5
    shared_memory: False
policy:
    use_cuda: True
    policy_type: 'qmix'
    import_names: ['nervex.policy.qmix']
    on_policy: True
    model:
        agent_num: 5
        obs_dim: 24
        global_obs_dim: 22
        action_dim: 4
        embedding_dim: 64
    learn:
        train_step: 100
        batch_size: 32
        agent_num: 5
        learning_rate: 0.0005
        weight_decay: 0.0001
        algo:
            target_update_theta: 0.001
            discount_factor: 0.99
    collect:
        traj_len: 'inf'
        unroll_len: 16
        agent_num: 5
        env_num: 8  # actor_env_num
    eval:
        agent_num: 5
        env_num: 5  # evaluator_env_num
    command:
        eps:
            type: 'exp'
            start: 1.0
            end: 0.05
            decay: 100000
replay_buffer:
    buffer_name: ['agent']
    agent:
        meta_maxlen: 5000
        max_reuse: 10
        min_sample_ratio: 1
actor:
    n_episode: 4
    traj_len: 1000  # smac_episode_max_length
    traj_print_freq: 100
    collect_print_freq: 100
evaluator:
    n_episode: 5
    eval_freq: 50
    stop_val: 0.7
learner:
    hook:
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 100
command:
    placeholder: 'placeholder'
