common:
    name: TestPendulumDdpg
    save_path: '.'
    load_path: ''
learner:
    learner_type: 'pendulum_ddpg'
    import_names: ['app_zoo.classic_control.pendulum.worker.learner.pendulum_ddpg_learner']
    use_cuda: False
    use_distributed: False
    max_iterations: 10
    unroll_len: 1
    learning_rate: 0.001
    weight_decay: 0.001
    reward_weights:
        'queue_len': 1.0
    data:
        batch_size: 4
        buffer_length: 10000
    ddpg:
        discount_factor: 0.95
        is_double: True
        dueling: True
        actor_update_freq: 1
env:
    placeholder: xxx
