from .pong_dqn_config import pong_dqn_config, pong_dqn_create_config
from .pong_dqn_envpool_config import pong_dqn_envpool_config, pong_dqn_envpool_create_config
from .pong_dqn_envpool_shink_model_config import pong_dqn_envpool_shink_model_config
from .pong_dqn_envpool_large_batch_config import pong_dqn_envpool_large_batch_config
from .pong_dqn_envpool_large_learning_config import pong_dqn_envpool_large_learning_config
from .pong_dqn_envpool_priority_config import pong_dqn_envpool_priority_config
from .pong_dqn_envpool_target_update_100_config import pong_dqn_envpool_target_update_100_config
from .pong_dqn_envpool_update_per_collect_5_config import pong_dqn_envpool_update_per_collect_5_config
from .pong_dqfd_config import pong_dqfd_config, pong_dqfd_create_config