common:
    name: SMACQMixConfig
    time_wrapper_type: cuda
    save_path: '.'
    load_path: ''
    algo_type: 'qmix'
learner:
    use_cuda: False
    use_distributed: False
    max_iterations: 10000000
    train_step: 1
    learning_rate: 0.0001
    weight_decay: 0.001
    eps:
        type: 'exp'
        start: 0.95
        end: 0.05
        decay: 10000
    data:
        batch_size: 64
        chunk_size: 64
        num_workers: 3
        max_reuse: 1
        buffer_length: 64
    qmix:
        discount_factor: 0.995
        traj_step: 32
    hook:
        save_ckpt_after_iter:
            name: save_ckpt_after_iter
            type: save_ckpt
            priority: 40
            position: after_iter
            ext_args:
                freq: 1000
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 10
model:
    embedding_dim: 128
env:
    agent_num: 8
actor:
    env_num: 16
    episode_num: 'inf'
    print_freq: 200
evaluator:
    env_num: 2
    episode_num: 'inf'
    total_episode_num: 4
    eval_step: 200
    stop_val: 0.7
