common:
    name: SMACQMixConfig
    time_wrapper_type: cuda
    save_path: '.'
    load_path: ''
    algo_type: 'qmix'
learner:
    use_cuda: True
    use_distributed: False
    max_iterations: 10000000
    train_step: 100
    learning_rate: 0.0005
    weight_decay: 0.0001
    eps:
        type: 'exp'
        start: 1.0
        end: 0.05
        decay: 200000
    data:
        batch_size: 32
        chunk_size: 32
        num_workers: 3
        max_reuse: 2
        buffer_length: 5000
        sample_ratio: 1
    qmix:
        discount_factor: 0.99
        traj_step: 16
    hook:
        save_ckpt_after_iter:
            name: save_ckpt_after_iter
            type: save_ckpt
            priority: 40
            position: after_iter
            ext_args:
                freq: 5000
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 10
model:
    embedding_dim: 64
env:
    map_name: '3s5z'
    agent_num: 8
actor:
    env_num: 8
    episode_num: 'inf'
    print_freq: 100
evaluator:
    env_num: 5
    episode_num: 'inf'
    total_episode_num: 2
    eval_step: 1000
    stop_val: 0.7
