common:
    name: SMACCOMAConfig
    time_wrapper_type: cuda
    save_path: '.'
    load_path: ''
    algo_type: 'coma'
learner:
    use_cuda: False
    use_distributed: False
    max_iterations: 10000000
    train_step: 1
    learning_rate: 0.0005
    weight_decay: 0.00001
    eps:
        type: 'exp'
        start: 0.5
        end: 0.01
        decay: 200000
    data:
        batch_size: 32
        chunk_size: 32
        num_workers: 3
        max_reuse: 1
        buffer_length: 64
        sample_ratio: 2
    coma:
        discount_factor: 0.99
        td_lambda: 0.8
        traj_step: 16
        value_weight: 1.0
        entropy_weight: 0.01
    hook:
        save_ckpt_after_iter:
            name: save_ckpt_after_iter
            type: save_ckpt
            priority: 40
            position: after_iter
            ext_args:
                freq: 5000
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 10
model:
    embedding_dim: 64
env:
    map_name: '3s5z'
    agent_num: 8
actor:
    env_num: 8
    episode_num: 'inf'
    print_freq: 100
evaluator:
    env_num: 5
    episode_num: 'inf'
    total_episode_num: 10
    eval_step: 100
    stop_val: 0.7
