common:
    save_path: '.'
actor:
    actor_type: 'sumowj3'
    import_names: ['app_zoo.sumo.worker.actor.sumowj3_actor_controller']
    print_freq: 1
    use_cuda: False
    communication:
        type: flask_fs  # ['single_machine', 'flask_fs']
        path_agent: '.'
        path_traj: '.'
        path_stat: '.'
        heartbeats_freq: 30
        upstream_ip: '127.0.0.1'
        upstream_port: 16296
env:
    placeholder: xxx
system:
    manager_ip: '127.0.0.1'
    manager_port: 16296
    coordinator_ip: '127.0.0.1'
    coordinator_port: 16297
    resume_dir: '.'
    actor_num: 1
    manager_resume_path:
    coordinator_resume_path:
    coordinator_check_dead_learner_freq: 300
    league_manager_port: 16298
