common:
    name: TestSumoDqn
    save_path: '.'
    load_path: ''
data:
    batch_size: 4
learner:
    learner_type: 'sumo_dqn'
    import_names: ['nervex.worker.learner.sumo_dqn_learner']
    use_cuda: False
    use_distributed: False
    max_iterations: 10
    batch_size: 4
    learning_rate: 0.001
    weight_decay: 0.001
    reward_weights:
        'queue_len': 1.0
    data:
        buffer_length: 10000
    dqn:
        update_target_freq: 300
        discount_factor: 0.99
        is_double: True
        dueling: True
env:
    placeholder: xxx
