common:
    name: TestSumoDqn
    save_path: '.'
    load_path: ''
learner:
    use_cuda: False
    use_distributed: False
    max_iterations: 10
    batch_size: 4
    learning_rate: 0.001
    weight_decay: 0.001
    reward_weights:
        'queue_len': 1.0
    dqn:
        total_frame_num: 1000000
        max_epoch_frame: 2000
        buffer_length: 10000
        update_target_freq: 300
        discount_factor: 0.99
        is_double: True
