@startuml

:Get the input dict D.;

:Get value a from dict D.;
:Set a1 as a + 1.;
if (Value a1's type is from 0 to 10) then (Yes.)
    :Item calculation success, \n**record this result a1**.;
else (No.)
    :The value a1 is not in range, \n**record this ValueError**.;
endif

:Get value b from dict D.;
:Set b1 as b * 2.;
if (Value b1's type is from 0 to 10) then (Yes.)
    :Item calculation success, \n**record this result b1**.;
else (No.)
    :The value b1 is not in range, \n**record this ValueError**.;
endif

if (No error recorded?) then (Yes.)
    :**Return recorded results as dict.**;
else (No.)
    :**Raise DictError, including the recorded errors.**;
    end
endif

stop

@enduml