@startuml

start

:Get the input value x.;

if (Value x's type is int?) then (Yes.)
else (No.)
    :The value x is invalid, **raise TypeError**.;
    end
endif

:**Return value x as result**.;

stop

@enduml