@startuml

start

:Get the input value x.;

:Set x1 as x + 1.;
:Set x2 as x1 * 2;

if (Value x2's type is from 0 to 10) then (Yes.)
else (No.)
    :The value x2 is not in range, **raise ValueError**.;
    end
endif

:**Return value x2 as result**.;

stop

@enduml