common:
    name: MujocoDdpgConfig
    save_path: '.'
    load_path: ''
env:
    env_id: 'InvertedDoublePendulum-v2'  # ['HalfCheetah-v1', 'Hopper-v1', 'Walker2d-v1']  # stop_val: 10500, 3700, 5300
    # 'Ant-v2': 5400
    # 'Reacher-v2': -3.1
    # 'InvPendulum-v2': 1000
    # 'InvDoublePendulum-v2': 9350
    frame_stack: 4
    is_train: True
    env_manager_type: 'subprocess'  # [base, subprocess]
    import_names: ['app_zoo.mujoco.envs.mujoco_env']
    env_type: 'mujoco'
    actor_env_num: 16
    evaluator_env_num: 8
    use_act_scale: True
policy:
    use_cuda: False
    policy_type: 'sac'
    import_names: ['nervex.policy.sac']
    on_policy: False
    use_priority: True
    model:
        obs_dim: 11
        action_dim: 1
        use_twin_q: True
    learn:
        train_step: 1
        batch_size: 256
        learning_rate_q: 0.0003
        learning_rate_value: 0.0003
        learning_rate_policy: 0.0003
        weight_decay: 0.0001
        ignore_done: True
        algo:
            target_theta: 0.005
            discount_factor: 0.99
            use_twin_q: True
            alpha: 0.2
            reparameterization: True
            policy_std_reg_weight: 0.001
            policy_mean_reg_weight: 0.001
    collect:
        traj_len: 1
        unroll_len: 1
        algo:
            noise_sigma: 0.1
    command:
        placeholder: 'placeholder'
replay_buffer:
    meta_maxlen: 100000
    max_reuse: 1024
    unroll_len: 1
    min_sample_ratio: 1
actor:
    n_sample: 24
    traj_len: 1
    traj_print_freq: 1000
    collect_print_freq: 1000
evaluator:
    n_episode: 8
    eval_freq: 1000
    stop_val: 10000
learner:
    hook:
        log_show:
            name: log_show
            type: log_show
            priority: 20
            position: after_iter
            ext_args:
                freq: 1000
command:
    placeholder: 'placeholder'
