# This workflow will check pytest
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: envpool_test

on: [push, pull_request]

jobs:
  test_envpooltest:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        python-version: [3.7, 3.8] # Envpool only supports python>=3.7

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: do_envpool_test
        run: |
          python -m pip install .
          python -m pip install ".[test,k8s]"
          python -m pip install ".[envpool]"
          python -m pip install transformers
          ./ding/scripts/install-k8s-tools.sh
          make envpooltest
